baseURL = "https://akbir.dev/"
languageCode = "en-uk"
title = "akbir khan"
theme = "hugo-theme-basic"
copyright = "Â© 2016-19 <a href='https://github.com/siegerts/hugo-theme-basic'>Hugo Theme Basic</a>. Made by <a href='https://twitter.com/siegerts'>@siegerts</a>."
googleAnalytics = "UA-59067982-2"
publishDir = "public"
enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":rocket:"
  twitter = "akbirkhan"
  description = "Blog and website of Akbir Khan, blogging mainly for tech. Opinions expressed are mine."

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "spotify"
  url = "https://open.spotify.com/user/akbir?si=uMCQZ-miSwKED_YTucb3fQ"

[[params.menu]]
  name = "twitter"
  url = "https://twitter.com/akbirkhan"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
